# Generated by Django 2.1.3 on 2018-11-26 12:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Food_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Food_Name', models.CharField(max_length=250)),
                ('Food_Pic', models.ImageField(upload_to='Restaurants/Pictures/Food')),
                ('Food_Price', models.IntegerField()),
                ('Food_Discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('FoodCategory_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FoodCategory_Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Restaurant_Name', models.CharField(max_length=250)),
                ('Restaurant_Logo', models.ImageField(upload_to='Restaurants/Pictures/Logo')),
                ('Restaurant_Area', models.CharField(max_length=250)),
                ('Restaurant_Pin', models.CharField(default=132658, max_length=6)),
                ('Restaurant_City', models.CharField(max_length=250)),
                ('Restaurant_State', models.CharField(max_length=250)),
                ('Restaurant_Num', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')])),
                ('Restaurant_Email', models.CharField(max_length=250)),
                ('Restaurant_Ratings_Count', models.IntegerField(default=0)),
                ('Restaurant_Rating', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(10))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='Food_Category_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.FoodCategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='Food_Res_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.Restaurant'),
        ),
    ]
