# Generated by Django 2.0.9 on 2018-11-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResProfile',
            fields=[
                ('Restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('Restaurant_Name', models.CharField(max_length=200)),
                ('Restaurant_Num', models.CharField(max_length=10, unique=True)),
                ('Restaurant_Area', models.CharField(max_length=105, unique=True)),
                ('Restaurant_City', models.CharField(max_length=200, unique=True)),
                ('Restaurant_State', models.CharField(max_length=200, unique=True)),
                ('Ratings_Count', models.IntegerField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
