# Generated by Django 2.0.9 on 2018-11-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resprofile',
            name='Ratings_Count',
            field=models.IntegerField(),
        ),
    ]
