# Generated by Django 2.0.9 on 2018-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_auto_20181116_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resprofile',
            name='Restaurant_Area',
            field=models.CharField(choices=[('thames', 'thames'), ('lambeth', 'lambeth'), ('southpark', 'southpark'), ('nova', 'nova')], max_length=105),
        ),
        migrations.AlterField(
            model_name='resprofile',
            name='Restaurant_City',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resprofile',
            name='Restaurant_State',
            field=models.CharField(max_length=200),
        ),
    ]
