# Generated by Django 2.1.3 on 2018-12-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_auto_20181202_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_Pic',
            field=models.ImageField(default='media/default_food.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Restaurant_Logo',
            field=models.ImageField(default='media/default_res.jpg', upload_to='media'),
        ),
    ]
