# Generated by Django 2.0.9 on 2018-11-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_auto_20181116_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resprofile',
            name='Ratings_Count',
        ),
    ]
