# Generated by Django 2.1.3 on 2018-12-11 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('Delivery_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Delivery_First_Name', models.CharField(max_length=250)),
                ('Delivery_Last_Name', models.CharField(max_length=250)),
                ('Delivery_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Delivery_Pin', models.CharField(default=0, max_length=6)),
                ('Delivery_Pic', models.ImageField(default='media/default_profile.jpg', upload_to='media')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Delivery.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Delivery.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.City'),
        ),
    ]
