# Generated by Django 2.1.3 on 2018-12-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('Delivery_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Delivery_First_Name', models.CharField(max_length=250)),
                ('Delivery_Last_Name', models.CharField(max_length=250)),
                ('Delivery_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Delivery_Area', models.CharField(choices=[('Cunninghum Road', 'Cunninghum Road'), ('Frazer Town', 'Frazer Town'), ('Whitefield', 'Whitefield'), ('Church Street', 'Church Street'), ('Egmore', 'Egmore'), ('Thirumalai', 'Thirumalai'), ('Anna Salai', 'Anna Salai'), ('Mount Road', 'Mount Road'), ('Connaught Place', 'Connaught Place'), ('Green Park', 'Green Park'), ('Nehru Road', 'Nehru Road'), ('Golf Course Road', 'Golf Course Road'), ('Park Street', 'Park Street'), ('Meredith Street', 'Meredith Street'), ('Chittaranjan Avenue', 'Chittaranjan Avenue'), ('S.N. Banerjee Road', 'S.N. Banerjee Road')], max_length=250)),
                ('Delivery_City', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata')], max_length=250)),
                ('Delivery_State', models.CharField(choices=[('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Delhi', 'Delhi'), ('West Bengal', 'West Bengal')], max_length=250)),
                ('Delivery_Pin', models.CharField(default=0, max_length=6)),
                ('Delivery_Pic', models.ImageField(default='media/default_profile.jpg', upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
