# Generated by Django 2.0.9 on 2018-11-16 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelProfile',
            fields=[
                ('Delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('Delivery_Fname', models.CharField(max_length=200)),
                ('Delivery_Lname', models.CharField(max_length=200)),
                ('Delivery_Num', models.CharField(max_length=10, unique=True)),
                ('Delivery_Area', models.CharField(max_length=105, unique=True)),
                ('Delivery_City', models.CharField(max_length=200, unique=True)),
                ('Delivery_State', models.CharField(max_length=200, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=100, unique=True)),
                ('Address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Address')),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Profile')),
            ],
        ),
    ]
