# Generated by Django 2.0.9 on 2018-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delprofile',
            name='Delivery_Area',
            field=models.CharField(choices=[('thames', 'thames'), ('lambeth', 'lambeth'), ('southpark', 'southpark'), ('nova', 'nova')], max_length=105),
        ),
        migrations.AlterField(
            model_name='delprofile',
            name='Delivery_City',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='delprofile',
            name='Delivery_State',
            field=models.CharField(max_length=200),
        ),
    ]
