# Generated by Django 2.1.3 on 2018-11-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=150)),
                ('Discount', models.FloatField()),
                ('Total_Price', models.FloatField()),
                ('Status', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='D_delivery.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='D_delivery.Customer')),
            ],
        ),
    ]
