# Generated by Django 2.1.3 on 2018-11-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_delivery', '0003_auto_20181111_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_ID',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
