# Generated by Django 2.0 on 2018-11-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Food_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Food_Name', models.CharField(max_length=150)),
                ('Food_Discount', models.FloatField()),
                ('Food_Price', models.FloatField()),
                ('Keywords', models.CharField(max_length=10000)),
                ('ratings_count', models.FloatField()),
                ('Rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Food_Category',
            fields=[
                ('ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='Food_Category_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='R_m.Food_Category'),
        ),
    ]
