# Generated by Django 2.1.3 on 2018-11-26 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurants', '0001_initial'),
        ('Delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Home', models.CharField(max_length=250)),
                ('Society', models.CharField(max_length=250)),
                ('Area', models.CharField(choices=[('Thames', 'Thames'), ('Lambeth', 'Lambeth'), ('Southpark', 'Southpark'), ('Nova', 'Nova')], max_length=250)),
                ('City', models.CharField(max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('Pin', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Quantity', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(10))),
                ('Item_Food_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Status', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(5))),
                ('Order_Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Customer_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Customer_FName', models.CharField(max_length=200)),
                ('Customer_LName', models.CharField(max_length=200)),
                ('Customer_Num', models.CharField(max_length=10, unique=True)),
                ('Customer_Email', models.EmailField(default='asd@rew.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Delivery_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Restaurant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='item',
            name='Item_Order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Order'),
        ),
        migrations.AddField(
            model_name='address',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Profile'),
        ),
    ]
