# Generated by Django 2.1.3 on 2018-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Area',
            field=models.CharField(choices=[('Thames', 'Thames'), ('Lambeth', 'Lambeth'), ('Southpark', 'Southpark'), ('Nova', 'Nova')], max_length=250),
        ),
    ]
