# Generated by Django 2.1.3 on 2018-12-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Area',
            field=models.CharField(choices=[('Cunninghum Road', 'Cunninghum Road'), ('Frazer Town', 'Frazer Town'), ('Whitefield', 'Whitefield'), ('Church Street', 'Church Street'), ('Egmore', 'Egmore'), ('Thirumalai', 'Thirumalai'), ('Anna Salai', 'Anna Salai'), ('Mount Road', 'Mount Road'), ('Connaught Place', 'Connaught Place'), ('Green Park', 'Green Park'), ('Nehru Road', 'Nehru Road'), ('Golf Course Road', 'Golf Course Road'), ('Park Street', 'Park Street'), ('Meredith Street', 'Meredith Street'), ('Chittaranjan Avenue', 'Chittaranjan Avenue'), ('S.N. Banerjee Road', 'S.N. Banerjee Road')], max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata')], max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(choices=[('Karnataka', 'Karnataka'), ('Channai', 'Channai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata')], max_length=250),
        ),
    ]
