# Generated by Django 2.1.3 on 2018-11-27 07:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Quantity', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(10))),
                ('Item_Food_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.Food')),
                ('Item_Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Order')),
            ],
        ),
    ]
