# Generated by Django 2.1.3 on 2018-11-27 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_Discount',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Total_Price',
            field=models.IntegerField(default=0),
        ),
    ]
