# Generated by Django 2.1.2 on 2018-11-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_cartitems_grandtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='GrandTotal',
        ),
    ]
