# Generated by Django 2.1.3 on 2018-11-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Food_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Food_Name', models.CharField(max_length=150)),
                ('Food_Discount', models.FloatField()),
                ('Food_Price', models.FloatField()),
                ('Keywords', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Category',
            fields=[
                ('ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Restaurant_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='Food_Category_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_search.Food_Category'),
        ),
        migrations.AddField(
            model_name='food',
            name='Food_ResID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='S_search.Restaurant'),
        ),
    ]
