# Generated by Django 2.1.3 on 2018-11-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Food_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Food_Name', models.CharField(max_length=150)),
                ('Food_Discount', models.FloatField()),
                ('Food_Price', models.FloatField()),
                ('Keywords', models.CharField(max_length=10000)),
                ('ratings_count', models.FloatField()),
                ('Rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Item_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Quantity', models.FloatField()),
                ('Price', models.FloatField()),
                ('Food_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='M_orders.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Discount', models.FloatField()),
                ('Total_Price', models.FloatField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='Order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='M_orders.Order'),
        ),
    ]
